FROM debian:jessie
MAINTAINER Naoaki Obiki

ARG username="9zilla"
ARG password="9zilla"

RUN apt-get update

#include "./include/plain.docker"
#include "./include/anyenv.docker"
#include "./include/ruby.docker"
#include "./include/nginx.docker"
#include "./include/node.docker"
#include "./include/mariadb-client.docker"
